version: "3.5"
networks:
    default:
        driver: bridge
        name: rinha-nginx-2024q1

services:
    api01: &api
        hostname: api01
        image: ffelipelimao/bank:8.1
        environment:
            - DB_HOST=db
            - DB_USER=user
            - DB_PASS=123
            - DB_NAME=bank
            - DB_PORT=3306
        ports:
            - "3001:3000"
        depends_on:
            - db
        deploy:
            resources:
                limits:
                    cpus: "0.37"
                    memory: "50MB"

    api02:
        <<: *api
        hostname: api02
        ports:
            - "3002:3000"
    nginx:
        image: nginx:latest
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api01
            - api02
        ports:
            - "9999:9999"
        deploy:
            resources:
                limits:
                    cpus: "0.2"
                    memory: "50MB"
                    
    db:
        image: mysql:latest
        hostname: db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: bank
            MYSQL_USER: user
            MYSQL_PASSWORD: 123
        ports:
            - "3306:3306"
        deploy:
            resources:
                limits:
                    cpus: "0.56"
                    memory: "400MB"
        volumes:
            - ./docker/script:/docker-entrypoint-initdb.d